In [1]:
!pip install numpy
import numpy as np


In [3]:
import numpy as np
X = np.array([
    [45, 50],
    [70, 65],
    [85, 80],
    [60, 58],
    [40, 42],
    [75, 70],
    [90, 85],
    [55, 60]
])

y = np.array([[48], [72], [88], [62], [44], [76], [91], [59]])


X = (X - X.mean(axis=0)) / X.std(axis=0)
y_mean = y.mean()
y_std = y.std()
y_norm = (y - y_mean) / y_std


In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)
    
np.random.seed(1)
W1 = np.random.randn(2, 3)
b1 = np.zeros((1, 3))

W2 = np.random.randn(3, 1)
b2 = np.zeros((1, 1))


print("🎯 Initial Weights and Biases:")
print("W1:\n", W1)
print("b1:\n", b1)
print("W2:\n", W2)
print("b2:\n", b2)




🎯 Initial Weights and Biases:
W1:
 [[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]]
b1:
 [[0. 0. 0.]]
W2:
 [[ 1.74481176]
 [-0.7612069 ]
 [ 0.3190391 ]]
b2:
 [[0.]]


In [5]:
def forward(X):
    global Z1, A1, Z2, A2
    Z1 = np.dot(X, W1) + b1
    A1 = sigmoid(Z1)
    Z2 = np.dot(A1, W2) + b2
    A2 = Z2  # Linear activation for regression
    return A2

# ==== 7. Backward Pass ====
def backward(X, y, output, lr=0.1):
    global W1, W2, b1, b2
    error = y - output
    d_output = error  # Derivative of linear is 1

    d_hidden = d_output.dot(W2.T) * sigmoid_derivative(A1)

    W2 += A1.T.dot(d_output) * lr
    b2 += np.sum(d_output, axis=0, keepdims=True) * lr

    W1 += X.T.dot(d_hidden) * lr
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * lr

In [6]:
final_preds = forward(X)
final_preds = final_preds * y_std + y_mean  # de-normalize

print("Predicted final scores:")
print(final_preds.round())

print("Actual final scores:")
print(y)



Predicted final scores:
[[75.]
 [81.]
 [79.]
 [80.]
 [77.]
 [80.]
 [79.]
 [74.]]
Actual final scores:
[[48]
 [72]
 [88]
 [62]
 [44]
 [76]
 [91]
 [59]]


In [7]:
epochs = 10  # keep small to observe clearly
for epoch in range(epochs):
    print(f"\n📘 Epoch {epoch+1}")
    
    # Forward pass
    output = forward(X)
    print("🔹 Output of forward pass (normalized):")
    print(output)

    # Backward pass
    backward(X, y_norm, output, lr=0.1)

    # Print updated weights after backprop
    print("🔧 Updated Weights and Biases:")
    print("W1:\n", W1)
    print("b1:\n", b1)
    print("W2:\n", W2)
    print("b2:\n", b2)
    
    # Compute and print loss
    loss = np.mean(np.square(y_norm - output))
    print(f"📉 Loss: {loss:.4f}")

# ==== 9. Final Predictions ====
print("\n✅ Final Predictions (Denormalized):")
preds = forward(X)
preds = preds * y_std + y_mean
print(preds.round())

print("🎯 Actual Final Scores:")
print(y)


📘 Epoch 1
🔹 Output of forward pass (normalized):
[[0.48396664]
 [0.80512569]
 [0.70751051]
 [0.75858197]
 [0.61637565]
 [0.74706529]
 [0.70772075]
 [0.42065639]]
🔧 Updated Weights and Biases:
W1:
 [[ 1.90918818 -0.74729556 -0.51942635]
 [-0.78411087  0.72901815 -2.29315774]]
b1:
 [[-0.20870246  0.09809526 -0.02013354]]
W2:
 [[ 1.57823342]
 [-0.97605853]
 [-0.22031196]]
b2:
 [[-0.52470029]]
📉 Loss: 1.3011

📘 Epoch 2
🔹 Output of forward pass (normalized):
[[-1.02853991]
 [-0.18893054]
 [ 0.14227534]
 [-0.56165923]
 [-1.00641974]
 [-0.05264787]
 [ 0.21001239]
 [-0.86274132]]
🔧 Updated Weights and Biases:
W1:
 [[ 2.02154771 -0.85023088 -0.52199503]
 [-0.67182586  0.62418314 -2.29535237]]
b1:
 [[-0.099014    0.01676662 -0.02789216]]
W2:
 [[ 1.83257906]
 [-0.80090056]
 [-0.20426353]]
b2:
 [[-0.1898352]]
📉 Loss: 0.4678

📘 Epoch 3
🔹 Output of forward pass (normalized):
[[-0.60061084]
 [ 0.47517174]
 [ 0.94274307]
 [-0.01288364]
 [-0.62690414]
 [ 0.66611973]
 [ 1.03693218]
 [-0.34871194]]
🔧 Up